services:
    express-app:
        build: .
        ports:
            - "4200:3000"
        env_file: ".env"

    mysql:
        image: mysql:latest
        restart: unless-stopped
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql-data:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: user
            PMA_PASSWORD: password
        ports:
            - "8080:80"
        depends_on:
            - mysql
            